CREATE TABLE С_FILE (
  ID         NUMBER PRIMARY KEY,
  FILE_NAME       VARCHAR(10) NOT NULL,
  FILE_FORMAT     VARCHAR(50) NOT NULL,
  FILE_SIZE       NUMBER NOT NULL,
  ID_STORAGE NUMBER,
  FOREIGN KEY(ID_STORAGE) REFERENCES STORAGE(ID)
)